# Generated by Django 4.1 on 2022-08-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='doctor',
        ),
        migrations.AddField(
            model_name='departments',
            name='doctor',
            field=models.ManyToManyField(related_name='department_doctor', to='Front.doctors'),
        ),
    ]
