# Generated by Django 4.1 on 2022-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0002_remove_departments_doctor_departments_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctors',
            name='department',
            field=models.ManyToManyField(related_name='doctor_department', to='Front.departments'),
        ),
    ]
