# Generated by Django 4.1 on 2022-08-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0003_about_us_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='active',
        ),
    ]
