# Generated by Django 4.1 on 2022-08-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0006_alter_about_provide_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_stats',
            name='title',
        ),
        migrations.AddField(
            model_name='about_stats',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_us',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.URLField(),
        ),
    ]
