# Generated by Django 4.1 on 2022-08-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0008_about_us_description_2_about_us_list_item_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='sub_title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
