# Generated by Django 4.1 on 2022-08-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0009_about_us_sub_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_provide',
        ),
    ]
