# Generated by Django 4.1 on 2022-08-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0010_delete_about_provide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.CharField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Services_banner',
        ),
    ]
