# Generated by Django 4.1 on 2022-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='.../static/front/assets/img/blank-profile-picture-973461_640.png', upload_to='User__Images'),
        ),
    ]
