# Generated by Django 4.1 on 2022-09-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='department',
        ),
        migrations.AddField(
            model_name='doctors',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_department', to='Hospital.departments'),
        ),
    ]
