# Generated by Django 4.1 on 2022-09-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_remove_doctors_department_doctors_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.doctors'),
        ),
    ]
