# Generated by Django 4.1 on 2022-09-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_departments_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatfields',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='department',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
