# Generated by Django 4.1 on 2022-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_remove_repeatfields_deleted_alter_doctors_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.CharField(max_length=150),
        ),
    ]
